[package]
authors = ["damon.chan <damon.chan@abc.hk>"]
edition = "2018"
readme = "README.org"
name = "ok"
version = "0.1.0"
links = "atom"

[workspace]
members = ["testsuite"]

[dependencies]
embedded-hal = "0.2"
nb = "0.1.2"
cortex-m = "0.6.3"
cortex-m-rt = "0.6.12"
cortex-m-rtic = "0.5.5"
cortex-m-semihosting = "0.3.3"
# panic-halt = "0.2.0"
heapless = "0.5.5"
cty = "0.2.1"
embedded-graphics = "0.6.1"
serde = { version = "1.0.116", default-features = false }
postcard = "0.5.1"

# rtt-target = { version = "0.2.2", features = ["cortex-m"] }
# panic-itm = "0.4.0"
# aux5 = { path = "auxiliary" }

# Uncomment for the panic example.
# panic-itm = "0.4.1"

# Uncomment for the allocator example.
# alloc-cortex-m = "0.3.5"

# Uncomment for the device example.
# Update `memory.x`, set target to `thumbv7em-none-eabihf` in `.cargo/config`,
# and then use `cargo build --examples device` to build it.
# [dependencies.stm32f3]
# features = ["stm32f303", "rt"]
# version = "0.7.1"

# this lets you use `cargo fix`!
# [dependencies.stm32f4]
# version = "0.11.0"
# features = ["stm32f407", "rt"]

[features]
# set logging levels here
default = [
  "defmt-default",
  # "dependency-a/defmt-trace",
  "defmt-trace",
]

# do NOT modify these features
defmt-default = []
defmt-trace = []
defmt-debug = []
defmt-info = []
defmt-warn = []
defmt-error = []

[dependencies.defmt]
git = "https://github.com/knurling-rs/defmt"
branch = "main"

[dependencies.defmt-rtt]
git = "https://github.com/knurling-rs/defmt"
branch = "main"

[dependencies.panic-probe]
git = "https://github.com/knurling-rs/probe-run"
branch = "main"

[dependencies.stm32f4xx-hal]
version = "0.8.3"
features = ["rt", "stm32f407"] # replace the model of your microcontroller here

[[bin]]
name = "ok"
test = false
bench = false

[lib]
name = "lib"
path = "src/lib.rs"

[profile.dev]
codegen-units = 1
debug = 2
debug-assertions = true # <-
incremental = false
opt-level = 3 # <-
overflow-checks = true # <-


[profile.release]
codegen-units = 1
debug = 2
debug-assertions = false # <-
incremental = false
lto = 'fat'
opt-level = 3 # <-
overflow-checks = false # <-

# do not optimize proc-macro crates = faster builds from scratch
[profile.dev.build-override]
codegen-units = 8
debug = false
debug-assertions = false
opt-level = 0
overflow-checks = false

[profile.release.build-override]
codegen-units = 8
debug = false
debug-assertions = false
opt-level = 0
overflow-checks = false

[build-dependencies]
bindgen = "0.55.1"
cc = "1.0"
